version: "3.8"
volumes:
  info-db-data:

services:
  info-db:
    container_name: info-db
    image: docker.io/library/postgres:12.1
    restart: always
    user: postgres
    environment:
      - TZ=Europe/Dublin
      - POSTGRES_USER=${INFO_DB_USERNAME:-admin}
      - POSTGRES_PASSWORD=${INFO_DB_PASSWORD:-Secret432}
      - POSTGRES_DB=${INFO_DB_NAME:-info}
      - PG_DATA=/data/postgres
    volumes:
      - "./info-db-data:/data/postgres"
      - "./info-db/sql/create_tables.sql:/data/sql/create_tables.sql"
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    #  interval: 10s
    #  timeout: 9s
    #  retries: 3
    #  start_period: 10s

  redis:
    container_name: info-redis
    image: docker.io/library/redis:latest
    user: nobody
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M

  frontend:
    container_name: info-frontend
    image: docker.io/library/alpine:latest
    user: ${DOCKER_USER:-root}
    build:
      dockerfile: frontend.Dockerfile
      context: .
      #target: build-static
      network: host
    init: true
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
    #depends_on:
    #  - info-db

# TODO Docs
# - https://github.com/mdn/developer-portal/blob/master/docker-compose.yml
# - https://medium.com/freestoneinfotech/simplifying-docker-compose-operations-using-makefile-26d451456d63
# - https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
# - https://runnable.com/docker/python/docker-compose-with-flask-apps
# - https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/
# - https://www.digitalocean.com/community/tutorials/how-to-use-templates-in-a-flask-application#
# - https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/
# 
# - Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
# - docker-compose build --progress plain --no-cache
# - docker-compose top
