version: '3.8'

networks:
  database:
    name: db-network
    driver: bridge
  backend:
    name: backend-network
    driver: bridge

volumes:
  db-volume:
    driver: local

services:

  database:
    container_name: info-db
    image: postgres:14.1-alpine
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    restart: unless-stopped
    environment:
      - TZ=Europe/Dublin
      - POSTGRES_USER=${INFO_DB_USERNAME:-admin}
      - POSTGRES_PASSWORD=${INFO_DB_PASSWORD:-Secret432}
      - POSTGRES_DB=${INFO_DB_NAME:-info_db}
      - PGDATA=/data/postgres
    ports:
      - '5432:5432'
    networks:
      - database
    volumes:
      - "./database/sql/create_tables.sql:/data/sql/create_tables.sql"
      - db-volume:/data/postgres
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${INFO_DB_USERNAME:-admin} -d ${INFO_DB_NAME:-info}"]
      interval: 10s
      timeout: 9s
      retries: 3
      start_period: 60s

  redis:
    container_name: info-redis
    image: docker.io/library/redis:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    user: nobody
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M

  frontend:
    container_name: info-frontend
    image: zlig/frontend:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    user: ${DOCKER_USER:-root}
    environment:
      - TZ=Europe/Dublin
      - POSTGRES_USER=${INFO_DB_USERNAME:-admin}
      - POSTGRES_PASSWORD=${INFO_DB_PASSWORD:-Secret432}
      - POSTGRES_DB=${INFO_DB_NAME:-info}
    build:
      dockerfile: Dockerfile
      context: frontend
      network: host
    init: true
    ports:
      - "8081:8081"
    networks:
      - database
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
    depends_on:
      - database

  backend:
    container_name: info-backend
    image: zlig/worker:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    user: ${DOCKER_USER:-root}
    environment:
      - TZ=Europe/Dublin
      - POSTGRES_USER=${INFO_DB_USERNAME:-admin}
      - POSTGRES_PASSWORD=${INFO_DB_PASSWORD:-Secret432}
      - POSTGRES_DB=${INFO_DB_NAME:-info}
    build:
      dockerfile: Dockerfile
      context: backend
      network: host
    init: true
    ports:
      - "8082:8082"
    profiles:
      - backend
    networks:
      - database
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
    depends_on:
      - redis

